name: post app
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: install python packages
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip packages
        run: python -m pip install --upgrade pip
      - name: install requirements
        run: pip install -r requirements.txt
      - name: install pytest packages
        run: pip install pytest
     