name: post app
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: install python packages
        uses: actions/setup-python@v2

     